var municipios = {
                "Amazonas":[
                    "Alto Orinoco (La Esmeralda)",
                    "Atabapo (San Fernando de Atabapo)",
                    "Atures (Puerto Ayacucho)",
                    "Autana (Isla Ratón)",
                    "Manapiare (San Juan de Manapiare)",
                    "Maroa (Maroa)",
                    "Río Negro (San Carlos de Río Negro)"
                    ],
                "Anzoátegui":[
                    "Anaco (Anaco)",
                    "Aragua (Aragua de Barcelona)",
                    "Bolívar (Barcelona)",
                    "Bruzual (Clarines)",
                    "Cajigal (Onoto)",
                    "Carvajal (Valle de Guanape)",
                    "Freites (Cantaura)",
                    "Guanipa (San José de Guanipa)",
                    "Guanta (Guanta)",
                    "Independencia (Soledad)",
                    "Libertad (San Mateo)",
                    "Sir Arthur McGregor (El Chaparro)",
                    "Miranda (Pariaguán)",
                    "Monagas (Mapire)",
                    "Peñalver (Puerto Píritu)",
                    "Píritu (Píritu)",
                    "San Juan de Capistrano (Boca de Uchire)",
                    "Santa Ana (Santa Ana)",
                    "Simón Rodríguez (El Tigre)",
                    "Sotillo (Puerto La Cruz)",
                    "Turístico Diego Bautista Urbaneja (Lechería)"
                    ],
                "Apure":[
                    "Achaguas (Achaguas)",
                    "Biruaca (Biruaca)",
                    "Pedro Camejo (San Juan de Payara)",
                    "Muñoz (Bruzual)",
                    "Páez (Guasdualito)",
                    "Rómulo Gallegos (Elorza)",
                    "San Fernando (San Fernando de Apure)"
                    ],
                "Aragua":[
                    "Alcántara (Santa Rita)",
                    "Bolívar (San Mateo)",
                    "Camatagua (Camatagua)",
                    "Girardot (Maracay)",
                    "Iragorry (El Limón)",
                    "Lamas (Santa Cruz de Aragua)",
                    "Libertador (Palo Negro)",
                    "Mariño (Turmero)",
                    "Michelena (Las Tejerías)",
                    "Ocumare de la Costa de Oro (Ocumare de la Costa)",
                    "Revenga (El Consejo)",
                    "Ribas (La Victoria)",
                    "San Casimiro (San Casimiro)",
                    "San Sebastián (San Sebastián de los Reyes)",
                    "Sucre (Cagua)",
                    "Tovar (Colonia Tovar)",
                    "Urdaneta (Barbacoas)",
                    "Zamora (Villa de Cura)"
                    ],
                "Barinas":[
                    "Alberto Arvelo Torrealba (Sabaneta)",
                    "Andrés Eloy Blanco (El Cantón)",
                    "Antonio José de Sucre (Socopó)",
                    "Arismendi (Arismendi)",
                    "Barinas (Barinas)",
                    "Bolívar (Barinitas)",
                    "Cruz Paredes (Barrancas)",
                    "Ezequiel Zamora (Santa Bárbara)",
                    "Obispos (Obispos)",
                    "Pedraza (Ciudad Bolivia)",
                    "Rojas (Libertad)",
                    "Sosa (Ciudad de Nutrias)"
                    ],
                "Bolívar":[
                    "Angostura (Ciudad Piar)",
                    "Angostura del Orinoco (Ciudad Bolívar)",
                    "Caroní (Ciudad Guayana)",
                    "Cedeño (Caicara del Orinoco)",
                    "Chien (El Palmar)",
                    "El Callao (El Callao)",
                    "Gran Sabana (Santa Elena de Uairén)",
                    "Piar (Upata)",
                    "Roscio (Guasipati)",
                    "Sifontes (El Dorado)",
                    "Sucre (Maripa)"
                    ],
                "Carabobo":[
                    "Bejuma (Bejuma)",
                    "Carlos Arvelo (Güigüe)",
                    "Diego Ibarra (Mariara)",
                    "Guacara (Guacara)",
                    "Juan José Mora (Morón)",
                    "Libertador (Tocuyito)",
                    "Los Guayos (Los Guayos)",
                    "Miranda (Miranda)",
                    "Montalbán (Montalbán)",
                    "Naguanagua (Naguanagua)",
                    "Puerto Cabello (Puerto Cabello)",
                    "San Diego (San Diego)",
                    "San Joaquín (San Joaquín)",
                    "Valencia (Valencia)"
                    ],
                "Cojedes":[
                    "Anzoátegui (Cojedes)",
                    "San Carlos (San Carlos)",
                    "Girardot (El Baúl)",
                    "Lima Blanco (Macapo)",
                    "Pao de San Juan Bautista (El Pao)",
                    "Ricaurte (Libertad)",
                    "Rómulo Gallegos (Las Vegas)",
                    "Tinaco (Tinaco)",
                    "Tinaquillo (Tinaquillo)"
                    ],
                "Distrito Capital":[
                    "Libertador (Caracas)"
                    ],
                "Falcón":[
                    "Acosta (San Juan de los Cayos)",
                    "Bolívar (San Luis)",
                    "Buchivacoa (Capatárida)",
                    "Carirubana (Punto Fijo)",
                    "Colina (La Vela de Coro)",
                    "Dabajuro (Dabajuro)",
                    "Democracia (Pedregal)",
                    "Falcón (Pueblo Nuevo)",
                    "Federación (Churuguara)",
                    "Iturriza (Chichiriviche)",
                    "Jacura (Jacura)",
                    "Los Taques (Santa Cruz de Los Taques)",
                    "Manaure (Yaracal)",
                    "Mauroa (Mene de Mauroa)",
                    "Miranda (Santa Ana de Coro)",
                    "Palmasola (Palmasola)",
                    "Petit (Cabure)",
                    "Píritu (Píritu)",
                    "San Francisco (Mirimire)",
                    "Sucre (La Cruz de Taratara)",
                    "Silva (Tucacas)",
                    "Tocópero (Tocópero)",
                    "Unión (Santa Cruz de Bucaral)",
                    "Urumaco (Urumaco)",
                    "Zamora (Puerto Cumarebo)"
                    ],
                "Guárico":[
                    "Camaguán (Camaguán)",
                    "Chaguaramas (Chaguaramas)",
                    "El Socorro (El Socorro)",
                    "Francisco de Miranda (Calabozo)",
                    "José Félix Ribas (Tucupido)",
                    "José Tadeo Monagas (Altagracia de Orituco)",
                    "Juan Germán Roscio (San Juan de los Morros)",
                    "Juan José Rondón (Las Mercedes)",
                    "Julián Mellado (El Sombrero)",
                    "Leonardo Infante (Valle de La Pascua)",
                    "Ortiz (Ortiz)",
                    "San Gerónimo de Guayabal (Guayabal)",
                    "San José de Guaribe (San José de Guaribe)",
                    "Santa María de Ipire (Santa María de Ipire)",
                    "Zaraza (Zaraza)"
                    ],
                "Lara":[
                    "Andrés Eloy Blanco (Sanare)",
                    "Crespo (Duaca)",
                    "Iribarren (Barquisimeto)",
                    "Jiménez (Quibor)",
                    "Morán (El Tocuyo)",
                    "Palavecino (Cabudare)",
                    "Simón Planas (Sarare)",
                    "Torres (Carora)",
                    "Urdaneta (Siquisique)"
                    ],
                "La Guaira":[
                    "Vargas (La Guaira)"
                    ],
                "Mérida":[
                    "Alberto Adriani (El Vigía)",
                    "Andrés Bello (La Azulita)",
                    "Antonio Pinto Salinas (Santa Cruz de Mora)",
                    "Aricagua (Aricagua)",
                    "Arzobispo Chacón (Canaguá)",
                    "Campo Elías (Ejido)",
                    "Caracciolo Parra Olmedo (Tucaní)",
                    "Cardenal Quintero (Santo Domingo)",
                    "Guaraque (Guaraque)",
                    "Julio Cesar Salas (Arapuey)",
                    "Justo Briceño (Torondoy)",
                    "Libertador (Mérida)",
                    "Miranda (Timotes)",
                    "Obispo Ramos de Lora (Santa Elena de Arenales)",
                    "Padre Noguera (Santa María de Caparo)",
                    "Pueblo Llano (Pueblo Llano)",
                    "Rangel (Mucuchíes)",
                    "Rivas Dávila (Bailadores)",
                    "Santos Marquina (Tabay)",
                    "Sucre (Lagunillas)",
                    "Tovar (Tovar)",
                    "Tulio Febres Cordero (Nueva Bolivia)",
                    "Zea (Zea)"
                    ],
                "Miranda":[
                    "Acevedo (Caucagua)",
                    "Andrés Bello (San José de Barlovento)",
                    "Baruta (Baruta)",
                    "Bolívar (San Francisco de Yare)",
                    "Brión (Higuerote)",
                    "Buroz (Mamporal)",
                    "Carrizal (Carrizal)",
                    "Chacao (Chacao)",
                    "Cristóbal Rojas (Charallave)",
                    "El Hatillo (El Hatillo)",
                    "Guaicaipuro (Los Teques)",
                    "Gual (Cúpira)",
                    "Independencia (Santa Teresa del Tuy)",
                    "Lander (Ocumare del Tuy)",
                    "Los Salias (San Antonio de los Altos)",
                    "Páez (Río Chico)",
                    "Paz Castillo (Santa Lucía)",
                    "Plaza (Guarenas)",
                    "Sucre (Petare)",
                    "Urdaneta (Cúa)",
                    "Zamora (Guatire)"
                    ],
                "Monagas":[
                    "Acosta (San Antonio de Capayacuar)",
                    "Aguasay (Aguasay)",
                    "Bolívar (Caripito)",
                    "Caripe (Caripe)",
                    "Cedeño (Caicara de Maturín)",
                    "Libertador (Temblador)",
                    "Maturín (Maturín)",
                    "Piar (Aragua de Maturín)",
                    "Punceres (Quiriquire)",
                    "Santa Bárbara (Santa Bárbara)",
                    "Sotillo (Barrancas del Orinoco)",
                    "Uracoa (Uracoa)",
                    "Zamora (Punta de Mata)"
                    ],
                "Nueva Esparta":[
                    "Antolín del Campo (Paraguachí)",
                    "Antonio Díaz (San Juan Bautista)",
                    "Arismendi (La Asunción)",
                    "García (El Valle)",
                    "Gómez (Santa Ana)",
                    "Macanao (Boca de Río)",
                    "Maneiro (Pampatar)",
                    "Marcano (Juan Griego)",
                    "Mariño (Porlamar)",
                    "Tubores (Punta de Piedras)",
                    "Villalba (San Pedro de Coche)"
                    ],
                "Portuguesa":[
                    "Agua Blanca (Agua Blanca)",
                    "Araure (Araure)",
                    "Esteller (Píritu)",
                    "Guanare (Guanare)",
                    "Guanarito (Guanarito)",
                    "José Vicente de Unda (Chabasquén)",
                    "Ospino (Ospino)",
                    "Páez (Acarigua)",
                    "Papelón (Papelón)",
                    "San Genaro de Boconoíto (Boconoíto)",
                    "San Rafael de Onoto (San Rafael de Onoto)",
                    "Santa Rosalía (El Playón)",
                    "Sucre (Biscucuy)",
                    "Turén (Villa Bruzual)"
                    ],
                "Sucre":[
                    "Andrés Eloy Blanco (Casanay)",
                    "Andrés Mata (San José de Aerocuar)",
                    "Arismendi (Río Caribe)",
                    "Benítez (El Pilar)",
                    "Bermúdez (Carúpano)",
                    "Bolívar (Marigüitar)",
                    "Cajigal (Yaguaraparo)",
                    "Cruz Salmerón Acosta (Araya)",
                    "Libertador (Tunapuy)",
                    "Mariño (Irapa)",
                    "Mejía (San Antonio del Golfo)",
                    "Montes (Cumanacoa)",
                    "Ribero (Cariaco)",
                    "Sucre (Cumaná)",
                    "Valdez (Güiria)"
                    ],
                "Táchira":[
                    "Andrés Bello (Cordero)",
                    "Antonio Rómulo Costa (Las Mesas)",
                    "Ayacucho (Colón)",
                    "Bolívar (San Antonio del Táchira)",
                    "Cárdenas (Táriba)",
                    "Córdoba (Santa Ana de Táchira)",
                    "Fernández (San Rafael del Piñal)",
                    "Francisco de Miranda (San José de Bolívar)",
                    "García de Hevia (La Fría)",
                    "Guásimos (Palmira)",
                    "Independencia (Capacho Nuevo)",
                    "Jáuregui (La Grita)",
                    "José María Vargas (El Cobre)",
                    "Junín (Rubio)",
                    "Libertad (Capacho Viejo)",
                    "Libertador (Abejales)",
                    "Lobatera (Lobatera)",
                    "Michelena (Michelena)",
                    "Panamericano (Coloncito)",
                    "Pedro María Ureña (Ureña)",
                    "Rafael Urdaneta (Delicias)",
                    "Samuel Dario Maldonado (La Tendida)",
                    "San Cristóbal (San Cristóbal)",
                    "San Judas Tadeo (Umuquena)",
                    "Seboruco (Seboruco)",
                    "Simón Rodríguez (San Simón)",
                    "Sucre (Queniquea)",
                    "Torbes (San Josecito)",
                    "Uribante (Pregonero)"
                    ],
                "Trujillo":[
                    "Andrés Bello (Santa Isabel)",
                    "Boconó (Boconó)",
                    "Bolívar (Sabana Grande)",
                    "Candelaria (Chejendé)",
                    "Carache (Carache)",
                    "Carvajal (Carvajal)",
                    "Escuque (Escuque)",
                    "Juan Vicente Campo Elías (Campo Elías)",
                    "La Ceiba (Santa Apolonia)",
                    "Márquez Cañizales (El Paradero)",
                    "Miranda (El Dividive)",
                    "Monte Carmelo (Monte Carmelo)",
                    "Motatán (Motatán)",
                    "Pampán (Pampán)",
                    "Pampanito (Pampanito)",
                    "Rangel (Betijoque)",
                    "Sucre (Sabana de Mendoza)",
                    "Trujillo (Trujillo)",
                    "Urdaneta (La Quebrada)",
                    "Valera (Valera)"
                    ],
                "Yaracuy":[
                    "Arístides Bastidas (San Pablo)",
                    "Bolívar (Aroa)",
                    "Bruzual (Chivacoa)",
                    "Cocorote (Cocorote)",
                    "Independencia (Independencia)",
                    "José Antonio Páez (Sabana de Parra)",
                    "La Trinidad (Boraure)",
                    "Manuel Monge (Yumare)",
                    "Nirgua (Nirgua)",
                    "Peña (Yaritagua)",
                    "San Felipe (San Felipe)",
                    "Sucre (Guama)",
                    "Urachiche (Urachiche)",
                    "Veroes (Farriar)"
                    ],
                "Zulia":[
                    "Almirante Padilla (El Toro)",
                    "Baralt (San Timoteo)",
                    "Cabimas (Cabimas)",
                    "Catatumbo (Encontrados)",
                    "Colón (San Carlos del Zulia)",
                    "Francisco Javier Pulgar (Pueblo Nuevo-El Chivo)",
                    "Guajira (Sinamaica)",
                    "Jesús Enrique Lossada (La Concepción)",
                    "Jesús María Semprún (Casigua El Cubo)",
                    "La Cañada de Urdaneta (Concepción)",
                    "Lagunillas (Ciudad Ojeda)",
                    "Machiques de Perijá (Machiques)",
                    "Mara (San Rafael del Moján)",
                    "Maracaibo (Maracaibo)",
                    "Miranda (Los Puertos de Altagracia)",
                    "Rosario de Perijá (La Villa del Rosario)",
                    "San Francisco (San Francisco)",
                    "Santa Rita (Santa Rita)",
                    "Simón Bolívar (Tía Juana)",
                    "Sucre (Bobures)",
                    "Valmore Rodríguez (Bachaquero)"
                    ],
            }